import { TipoModeloRelatorio, ModeloRelatorioConfig } from '../../types';

export const MODELOS_RELATORIOS: ModeloRelatorioConfig[] = [
  {
    id: 'geral_pedidos',
    numero: 1,
    titulo: 'Relatório Geral de Pedidos',
    descricao: 'Visão panorâmica de todos os pedidos com status, comitê, materiais e valores',
    categoria: 'pedidos',
    icone: 'ClipboardList',
  },
  {
    id: 'pedidos_cliente',
    numero: 2,
    titulo: 'Pedidos por Cliente / Comitê',
    descricao: 'Consolidado de solicitações agrupadas por candidato, comitê eleitoral ou cliente',
    categoria: 'pedidos',
    icone: 'Building2',
  },
  {
    id: 'pedidos_periodo',
    numero: 3,
    titulo: 'Pedidos por Período / Entrada',
    descricao: 'Evolução cronológica de entradas de pedidos por data de cadastro e registro',
    categoria: 'pedidos',
    icone: 'Calendar',
  },
  {
    id: 'agendamentos_cronograma',
    numero: 4,
    titulo: 'Relatório de Agendamentos por Data e Horário',
    descricao: 'Cronograma completo de agendamentos de clientes, comitês e entregas com data e hora programada',
    categoria: 'pedidos',
    icone: 'CalendarClock',
  },
  {
    id: 'materiais_solicitados',
    numero: 5,
    titulo: 'Materiais Solicitados',
    descricao: 'Volume total de santinhos, praguinhas, bandeiras e lonas solicitados',
    categoria: 'materiais',
    icone: 'Package',
  },
  {
    id: 'materiais_separados',
    numero: 6,
    titulo: 'Materiais Separados (Picking)',
    descricao: 'Materiais conferidos e embalados pela equipe de separação no armazém',
    categoria: 'materiais',
    icone: 'CheckSquare',
  },
  {
    id: 'materiais_liberados',
    numero: 7,
    titulo: 'Materiais Liberados pela Expedição',
    descricao: 'Lotes liberados para despacho, conferência de saída e rotas de entrega',
    categoria: 'materiais',
    icone: 'Truck',
  },
  {
    id: 'pedidos_pendentes_atrasados',
    numero: 8,
    titulo: 'Pedidos Pendentes e Atrasados',
    descricao: 'Acompanhamento de pedidos com prazo crítico, pendências ou em atraso',
    categoria: 'pedidos',
    icone: 'AlertTriangle',
  },
  {
    id: 'entregas_realizadas',
    numero: 9,
    titulo: 'Entregas Realizadas com Comprovante (POD)',
    descricao: 'Comprovações físicas, fotos de recebimento, assinaturas e geolocalização TSE',
    categoria: 'entregas',
    icone: 'ShieldCheck',
  },
  {
    id: 'entregas_pendentes_canceladas',
    numero: 10,
    titulo: 'Entregas Pendentes, Canceladas ou Devolvidas',
    descricao: 'Insucessos de entrega, ocorrências de endereço e devoluções à base',
    categoria: 'entregas',
    icone: 'XCircle',
  },
  {
    id: 'rotas_horarios',
    numero: 11,
    titulo: 'Rotas e Horários de Saída e Chegada',
    descricao: 'Tempos de trânsito, trajetos por zona eleitoral e horários de despacho',
    categoria: 'entregas',
    icone: 'Navigation',
  },
  {
    id: 'desempenho_motoboys',
    numero: 12,
    titulo: 'Desempenho dos Motoboys',
    descricao: 'Produtividade por entregador, taxa de sucesso, tempo médio e avaliações',
    categoria: 'entregas',
    icone: 'Award',
  },
  {
    id: 'estoque_atual',
    numero: 13,
    titulo: 'Estoque Atual & Posição Física',
    descricao: 'Saldos disponíveis, reservados para pedidos, avariados e valorização total',
    categoria: 'estoque',
    icone: 'Boxes',
  },
  {
    id: 'entradas_saidas_estoque',
    numero: 14,
    titulo: 'Entradas e Saídas do Estoque (Kardex)',
    descricao: 'Histórico completo de movimentações, notas fiscais, compras e baixas',
    categoria: 'estoque',
    icone: 'ArrowLeftRight',
  },
  {
    id: 'produtos_estoque_baixo',
    numero: 15,
    titulo: 'Produtos com Estoque Baixo / Crítico',
    descricao: 'Materiais que atingiram ou estão abaixo do estoque de segurança mínimo',
    categoria: 'estoque',
    icone: 'AlertOctagon',
  },
  {
    id: 'produtos_sem_estoque',
    numero: 16,
    titulo: 'Produtos Esgotados / Sem Estoque',
    descricao: 'Itens com saldo zerado e pedidos dependentes aguardando produção',
    categoria: 'estoque',
    icone: 'MinusCircle',
  },
  {
    id: 'inventario_materiais',
    numero: 17,
    titulo: 'Inventário Físico de Materiais',
    descricao: 'Conferências periódicas, contagens de armazém e divergências de saldo',
    categoria: 'estoque',
    icone: 'FileSpreadsheet',
  },
  {
    id: 'custos_operacionais',
    numero: 18,
    titulo: 'Custos Operacionais de Logística',
    descricao: 'Demonstrativo de fretes, diárias, combustíveis, embalagens e insumos',
    categoria: 'financeiro',
    icone: 'DollarSign',
  },
  {
    id: 'pagamentos_remuneracoes',
    numero: 19,
    titulo: 'Pagamentos e Remunerações',
    descricao: 'Repasses a motoboys, recebimentos de comitês e conciliação financeira',
    categoria: 'financeiro',
    icone: 'CreditCard',
  },
  {
    id: 'usuario_equipe_setor',
    numero: 20,
    titulo: 'Atividades por Usuário, Equipe ou Setor',
    descricao: 'Registros operacionais de atendimento, estoque, separação e expedição',
    categoria: 'auditoria',
    icone: 'Users',
  },
  {
    id: 'historico_alteracoes',
    numero: 21,
    titulo: 'Histórico Completo de Alterações (Auditoria)',
    descricao: 'Trilha imutável de logs de segurança, edições de pedidos e acessos',
    categoria: 'auditoria',
    icone: 'History',
  },
];
